all:
	g++ -lwiringPi -lpthread finalProject.cpp finalProject.h rtu.cpp -o rtu -Wall -std=c++11
	g++ -lwiringPi -lpthread finalProject.cpp finalProject.h historian.cpp -o historian -Wall -std=c++11
	g++ -lwiringPi -lpthread finalProject.cpp finalProject.h historianTest.cpp -o historianTest -Wall -std=c++11 
rtu: 
	g++ -lwiringPi -lpthread finalProject.cpp finalProject.h rtu.cpp -o rtu -Wall -std=c++11
historian:
	g++ -lwiringPi -lpthread finalProject.cpp finalProject.h historian.cpp -o historian -Wall -std=c++11